import { Request, Response } from 'express';

export const chatWithAI = (req: Request, res: Response) => {
    const { message } = req.body;
    res.json({
        success: true,
        message: 'Chat response generated successfully',
        data: {
            reply: `This is a response from the local ExamRedi AI. You asked: "${message}". I'm here to help you study more effectively!`
        },
        statusCode: 200
    });
};

export const generateStudyGuide = (req: Request, res: Response) => {
    const { topic } = req.body;
    res.json({
        success: true,
        message: 'Study guide generated successfully',
        data: {
            guide: `# Study Guide: ${topic}\n\n## 1. Core Concepts\nDetailed explanation of the fundamental principles of ${topic}.\n\n## 2. Important Formulas\nAny relevant mathematical or scientific formulas used in ${topic}.\n\n## 3. Practice Questions\n- Question 1: How does X affect Y?\n- Question 2: Define Z in the context of ${topic}.\n\n*Generated by ExamRedi AI (Local Backend)*`
        },
        statusCode: 200
    });
};

export const researchTopic = (req: Request, res: Response) => {
    const { query } = req.body;
    res.json({
        success: true,
        message: 'Research results retrieved successfully',
        data: {
            result: `### Research Results for "${query}"\n\n- **Key Fact:** ${query} is essential for understanding advanced concepts in this subject.\n- **Related Topic:** Exploration of how ${query} connects with other modules.\n- **Learning Resource:** [Link to simulated resource]\n\n*Research provided by ExamRedi AI.*`
        },
        statusCode: 200
    });
};
